services:

  mailer:
    image: axllent/mailpit
    container_name: mailpit-news
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - webdev

  database:
    image: mariadb
    container_name: mariadb-news
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql/data:rw
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: 'news.db'
    networks:
      - webdev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-news
    depends_on:
      - database
    ports:
      - 8085:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - webdev

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq-news
    environment:
      RABBITMQ_USER: 'guest'
      RABBITMQ_PASS: 'guest'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - webdev

  redis:
    image: redis:5-alpine
    container_name: redis-news
    ports: [ "6379:6379" ]
    networks:
      - webdev




volumes:
  db-data:
networks:
  webdev:

